name: didur_seed
description: Didur Dev Seed
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  flutter_native_splash: ^2.2.7

  #
  auto_route: ^8.1.3
  collection: ^1.18.0
  crypto: ^3.0.3
  firebase_analytics: ^10.10.7
  firebase_crashlytics: ^3.5.7
  firebase_remote_config: ^4.4.7
  flex_color_scheme: ^7.3.1
  flutter_animate: ^4.5.0
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  in_app_review: ^2.0.9
  injectable: ^2.4.1
  json_annotation: ^4.9.0
  mask_text_input_formatter: ^2.9.0
  package_info_plus: ^8.0.0
  purchases_flutter: ^8.1.4
  shared_preferences: ^2.2.3
  sign_in_with_apple: ^6.1.0
  supabase_flutter: ^2.5.3
  universal_html: ^2.2.4
  universal_io: ^2.2.2
  url_launcher: ^6.2.6
  firebase_core: ^2.32.0
  #

  flutter_gen: any
dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.4
  flutter_gen_runner: ^5.2.0

  #
  build_runner: ^2.4.9
  auto_route_generator: ^8.0.0
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0

  # Icone
  flutter_launcher_icons: ^0.13.1

flutter_gen:
  output: lib/app/gen/
  line_length: 120

  # Optional
  integrations:
    flutter_svg: true
    # flare_flutter: true
    # rive: true

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/icons/
    - assets/images/

scripts:
  build-clean: flutter packages pub run build_runner clean
  build: flutter packages pub run build_runner build --delete-conflicting-outputs
  generate-icons-d: flutter pub run flutter_launcher_icons -f flutter_launcher_icons-development
  generate-icons-p: flutter pub run flutter_launcher_icons -f flutter_launcher_icons-production
  generate-icons-s: flutter pub run flutter_launcher_icons -f flutter_launcher_icons-staging
  generate-splash: dart run flutter_native_splash:create